### ISSUE TITLE
Implement a command line config source

### ISSUE THREAD

**Issue by msm-code** [bwindsor/typed-config#16]
First of all, great project, thanks for maintaining it.

I think about having three ways to specify config keys to my application, in this order of precedence:

* as command line parameter, like `--redis_port=1234`
* as environment variable, like `REDIS_PORT=1234`
* via the config file like
```
[redis]
port=1234
```

From what I've seen, it seems to be relatively straightforward to implement a command line config source. Does it sound like a good feature for this project?

**Comment by bwindsor** [comment]
Hi @msm-code, I must have missed this and only just spotted it now - I think this should be possible and I agree it would be a good feature for the project to have! Were you imagining that the command line interface would simply be arguments in the form `--<section_name>_<key_name>` as in your example or is there any more complexity involved?

I know it was over a year since you posted this so if it's no longer relevant to you no worries - it's a nice idea and I hope that I will manage to add it at some point.

**Comment by bwindsor** [comment]
I've added a simple implementation of this now, so closing.
